name: xlints
description: Flutter performance linter - mendeteksi pola kode yang menyebabkan performa aplikasi buruk dan memberikan rekomendasi perbaikan.
version: 1.0.0
repository: https://github.com/anonimeact/flutter-xlints.git

environment:
  sdk: ^3.10.4

dependencies:
  analyzer: ^6.0.0
  custom_lint: ^0.6.0
  custom_lint_builder: ^0.6.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.0
  test: ^1.25.6
